version: 2.0.{build}
os: Visual Studio 2015

install:
    - nuget restore

build:
  project: Pyramid2000.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: D3xk3zhufhpC3ZTVEFQT4jGsSmEWWzNJdJsAUu2wK2EARb9Z3LO4Uaubq7HM007j

after_test: 
# generate report for NUnit testing framework:
    -cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single Pyramid2000EngineTests\bin\debug\Pyramid2000EngineTests.dll" -output:coverage.xml

    -cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml