version: 2.0.{build}
os: Visual Studio 2017

environment:
    COVERALLS_REPO_TOKEN:  
       secure: D3xk3zhufhpC3ZTVEFQT4jGsSmEWWzNJdJsAUu2wK2EARb9Z3LO4Uaubq7HM007j

install:
    - nuget restore

build_script:
    - choco install "msbuild-sonarqube-runner" -y
    - MSBuild.SonarQube.Runner.exe begin /k:"Pyramid2000" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=4f25726209d441b4d8223ac458fdb72d5710c7ed"
    - msbuild "Pyramid2000.sln" /verbosity:normal /p:Platform=x64;AppxBundle=Never
    - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=4f25726209d441b4d8223ac458fdb72d5710c7ed"

test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"nunit3-console.exe" -targetargs:"/domain:single /result:myresults.xml;format=AppVeyor Pyramid2000EngineTests\bin\debug\Pyramid2000EngineTests.dll" -output:coverage.xml -returntargetcode

after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml