version: 2.0.{build}
os: Visual Studio 2015

environment:
    COVERALLS_REPO_TOKEN:  
       secure: D3xk3zhufhpC3ZTVEFQT4jGsSmEWWzNJdJsAUu2wK2EARb9Z3LO4Uaubq7HM007j

install:
    - nuget restore

build:
  project: Pyramid2000.sln
  verbosity: minimal

test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Console.3.0.1\tools\nunit3-console.exe" -targetargs:"/domain:single  Pyramid2000EngineTests\bin\debug\Pyramid2000EngineTests.dll" -output:coverage.xml

after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml