//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid2000Engine {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pyramid2000Engine.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A TWELVE FOOT BEAN STALK STRETCHING UP OUT OF THE PIT, BELLOWING &quot;WATER... WATER...&quot;.
        /// </summary>
        internal static string Item_Description_Beanstalk {
            get {
                return ResourceManager.GetString("Item_Description_Beanstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRASS LANTERN.
        /// </summary>
        internal static string Item_Description_Brass_Lantern {
            get {
                return ResourceManager.GetString("Item_Description_Brass_Lantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASTY FOOD.
        /// </summary>
        internal static string Item_Description_Food {
            get {
                return ResourceManager.GetString("Item_Description_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS FOOD HERE..
        /// </summary>
        internal static string Item_Description_Food_Here {
            get {
                return ResourceManager.GetString("Item_Description_Food_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A GIGANTIC BEAN STALK STRETCHING ALL THE WAY UP TO THE HOLE..
        /// </summary>
        internal static string Item_Description_Gigantic_Beanstalk {
            get {
                return ResourceManager.GetString("Item_Description_Gigantic_Beanstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A LAMP SHINING NEARBY..
        /// </summary>
        internal static string Item_Description_Shining_Lamp {
            get {
                return ResourceManager.GetString("Item_Description_Shining_Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A SHINY BRASS LAMP NEARBY..
        /// </summary>
        internal static string Item_Description_Shiny_Lamp {
            get {
                return ResourceManager.GetString("Item_Description_Shiny_Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A STONE BRIDGE NOW SPANS THE BOTTOMLESS PIT..
        /// </summary>
        internal static string Item_Description_Stone_Bridge {
            get {
                return ResourceManager.GetString("Item_Description_Stone_Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A TINY PLANT IN THE PIT, MURMURING &quot;WATER, WATER, ...&quot;.
        /// </summary>
        internal static string Item_Description_Tiny_Plant {
            get {
                return ResourceManager.GetString("Item_Description_Tiny_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS A MASSIVE VENDING MACHINE HERE. THE INSTRUCTIONS ON IT READ &quot;DROP COINS HERE TO RECEIVE FRESH BATTERIES&quot;..
        /// </summary>
        internal static string Item_Description_Vending_Machine {
            get {
                return ResourceManager.GetString("Item_Description_Vending_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATER IN THE BOTTLE.
        /// </summary>
        internal static string Item_Description_Water {
            get {
                return ResourceManager.GetString("Item_Description_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS WATER IN THE BOTTLE..
        /// </summary>
        internal static string Item_Description_Water_In_Bottle {
            get {
                return ResourceManager.GetString("Item_Description_Water_In_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HUGE GREEN FIERCE SERPENT BARS THE WAY!.
        /// </summary>
        internal static string Item_Descrption_Serpent {
            get {
                return ResourceManager.GetString("Item_Descrption_Serpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE ALREADY CARRYING IT..
        /// </summary>
        internal static string Message_Already_Carrying {
            get {
                return ResourceManager.GetString("Message_Already_Carrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  YOU CAN&apos;T CARRY ANYTHING MORE. YOU&apos;LL HAVE TO DROP SOMETHING FIRST..
        /// </summary>
        internal static string Message_Cant_Carry_Anymore {
            get {
                return ResourceManager.GetString("Message_Cant_Carry_Anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORRY, BUT I NO LONGER SEEM TO REMEMBER HOW IT WAS YOU GOT HERE..
        /// </summary>
        internal static string Message_Cant_Go_Back {
            get {
                return ResourceManager.GetString("Message_Cant_Go_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I DON&apos;T KNOW IN FROM OUT HERE. USE COMPASS POINTS..
        /// </summary>
        internal static string Message_Cant_Go_In_Or_Out {
            get {
                return ResourceManager.GetString("Message_Cant_Go_In_Or_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I AM UNSURE HOW YOU ARE FACING. USE COMPASS POINTS..
        /// </summary>
        internal static string Message_Cant_Go_Left_Or_Right {
            get {
                return ResourceManager.GetString("Message_Cant_Go_Left_Or_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THERE IS NO WAY FOR YOU TO GO THAT DIRECTION..
        /// </summary>
        internal static string Message_Cant_Go_That_Way {
            get {
                return ResourceManager.GetString("Message_Cant_Go_That_Way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I DON&apos;T KNOW HOW TO APPLY THAT WORD HERE..
        /// </summary>
        internal static string Message_Inapplicable_Word {
            get {
                return ResourceManager.GetString("Message_Inapplicable_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU&apos;RE NOT CARRYING ANYTHING..
        /// </summary>
        internal static string Message_Not_Carrying_Anything {
            get {
                return ResourceManager.GetString("Message_Not_Carrying_Anything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU AREN&apos;T CARRYING IT..
        /// </summary>
        internal static string Message_Not_Carrying_It {
            get {
                return ResourceManager.GetString("Message_Not_Carrying_It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I SEE NO {0} HERE..
        /// </summary>
        internal static string Message_Not_Here {
            get {
                return ResourceManager.GetString("Message_Not_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTHING HAPPENS..
        /// </summary>
        internal static string Message_Nothing_Happens {
            get {
                return ResourceManager.GetString("Message_Nothing_Happens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  OK.
        /// </summary>
        internal static string Message_OK {
            get {
                return ResourceManager.GetString("Message_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE PLANT HAS EXCEPTIONALLY DEEP ROOTS AND CANNOT BE PULLED FREE.
        /// </summary>
        internal static string Message_Plant_Has_Deep_Roots {
            get {
                return ResourceManager.GetString("Message_Plant_Has_Deep_Roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string Message_Prompt {
            get {
                return ResourceManager.GetString("Message_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU HAVE SCORED {0} OUT OF 220..
        /// </summary>
        internal static string Message_Score {
            get {
                return ResourceManager.GetString("Message_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USING {0} TURNS..
        /// </summary>
        internal static string Message_Turns_Used {
            get {
                return ResourceManager.GetString("Message_Turns_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO PYRAMID 2000!!.
        /// </summary>
        internal static string Message_Welcome {
            get {
                return ResourceManager.GetString("Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE IN THE DESERT..
        /// </summary>
        internal static string Room_Description_In_The_Desert {
            get {
                return ResourceManager.GetString("Room_Description_In_The_Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE STANDING BEFORE THE ENTRANCE OF A PYRAMID. AROUND YOU IS A DESERT..
        /// </summary>
        internal static string Room_Description_Outside_Pyramid {
            get {
                return ResourceManager.GetString("Room_Description_Outside_Pyramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE STANDING IN THE ENTRANCE OF THE PYRAMID. A HOLE IN THE FLOOR LEADS TO A PASSAGE BENEATH THE SURFACE..
        /// </summary>
        internal static string Room_Description_Pyramid_Entrance {
            get {
                return ResourceManager.GetString("Room_Description_Pyramid_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU ARE IN A SMALL CHAMBER BENEATH A HOLE FROM THE SURFACE. A LOW CRAWL LEADS INWARDS TO THE WEST. HIEROGLYPHICS ON THE WALL TRANSLATE, &quot;CURSE ALL WHO ENTER THIS SACRED CRYPT.&quot;.
        /// </summary>
        internal static string Room_Description_Small_Chamber {
            get {
                return ResourceManager.GetString("Room_Description_Small_Chamber", resourceCulture);
            }
        }
    }
}
