//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid2000.Engine {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pyramid2000.Engine.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already carrying it..
        /// </summary>
        internal static string AlreadyCarryingIt {
            get {
                return ResourceManager.GetString("AlreadyCarryingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t carrying it..
        /// </summary>
        internal static string ArentCarryingIt {
            get {
                return ResourceManager.GetString("ArentCarryingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A huge green fierce serpent bars the way!.
        /// </summary>
        internal static string BarredBySerpent {
            get {
                return ResourceManager.GetString("BarredBySerpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bird statue comes to life and attacks the serpent and in an astounding flurry, drives the serpent away. The bird turns back into a statue..
        /// </summary>
        internal static string BirdAlive {
            get {
                return ResourceManager.GetString("BirdAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bottle is already full..
        /// </summary>
        internal static string BottleAlreadyFull {
            get {
                return ResourceManager.GetString("BottleAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass Lantern.
        /// </summary>
        internal static string BrassLantern {
            get {
                return ResourceManager.GetString("BrassLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stone bridge now spans the bottomless pit..
        /// </summary>
        internal static string BridgeAppears {
            get {
                return ResourceManager.GetString("BridgeAppears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone bridge has retracted!.
        /// </summary>
        internal static string BridgeRetracted {
            get {
                return ResourceManager.GetString("BridgeRetracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the pit with a broken neck..
        /// </summary>
        internal static string BrokenNeck {
            get {
                return ResourceManager.GetString("BrokenNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t carry anything more. You&apos;ll have to drop something first..
        /// </summary>
        internal static string CantCarryAnymore {
            get {
                return ResourceManager.GetString("CantCarryAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no way across the bottomless pit..
        /// </summary>
        internal static string CantCrossPit {
            get {
                return ResourceManager.GetString("CantCrossPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t fit through the two-inch slit!.
        /// </summary>
        internal static string CantFitThroughTwoInchSlit {
            get {
                return ResourceManager.GetString("CantFitThroughTwoInchSlit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve climbed up the plant and out of the pit..
        /// </summary>
        internal static string ClimbedPlant {
            get {
                return ResourceManager.GetString("ClimbedPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clamber up the plant and scurry through the hole at the top..
        /// </summary>
        internal static string ClimbPlant {
            get {
                return ResourceManager.GetString("ClimbPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crack is far too small for you to follow..
        /// </summary>
        internal static string CrackTooSmall {
            get {
                return ResourceManager.GetString("CrackTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled around in some little holes and found your way blocked by a fallen slab. You are now back in the main passage..
        /// </summary>
        internal static string CrawledAround {
            get {
                return ResourceManager.GetString("CrawledAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled around in some little holes and wound up back in the main passage..
        /// </summary>
        internal static string CrawledAroundBackToMainPassage {
            get {
                return ResourceManager.GetString("CrawledAroundBackToMainPassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled through a very low wide passage parallel to and north of the hall of gods..
        /// </summary>
        internal static string CrawlToPassage {
            get {
                return ResourceManager.GetString("CrawlToPassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I respectfully suggest you go across the bridge instead of jumping..
        /// </summary>
        internal static string CrossDontJump {
            get {
                return ResourceManager.GetString("CrossDontJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead end..
        /// </summary>
        internal static string DeadEnd {
            get {
                return ResourceManager.GetString("DeadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the desert..
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t make it..
        /// </summary>
        internal static string DidntMakeIt {
            get {
                return ResourceManager.GetString("DidntMakeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a small statue box discarded nearby..
        /// </summary>
        internal static string DiscardedStatueBox {
            get {
                return ResourceManager.GetString("DiscardedStatueBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dome is unclimbable..
        /// </summary>
        internal static string DomeUnclimbable {
            get {
                return ResourceManager.GetString("DomeUnclimbable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t be ridiculous!.
        /// </summary>
        internal static string DontBeRidiculous {
            get {
                return ResourceManager.GetString("DontBeRidiculous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that word..
        /// </summary>
        internal static string DontKnowThatWord {
            get {
                return ResourceManager.GetString("DontKnowThatWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what you mean..
        /// </summary>
        internal static string DontKnowWhatYouMean {
            get {
                return ResourceManager.GetString("DontKnowWhatYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t understand..
        /// </summary>
        internal static string DontUnderstand {
            get {
                return ResourceManager.GetString("DontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something you&apos;re carrying won&apos;t fit through the tunnel with you. You&apos;d best take inventory and drop something..
        /// </summary>
        internal static string DropSomething {
            get {
                return ResourceManager.GetString("DropSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You fell into a pit and broke every bone in your body..
        /// </summary>
        internal static string FellIntoPit {
            get {
                return ResourceManager.GetString("FellIntoPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are now some fresh batteries here..
        /// </summary>
        internal static string FreshBatteries {
            get {
                return ResourceManager.GetString("FreshBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a gigantic beam stalk stretching all the way up to the hole..
        /// </summary>
        internal static string GiganticBeanStalk {
            get {
                return ResourceManager.GetString("GiganticBeanStalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh dear, you seem to have gotten yourself killed.  I might be able to help you out, but I&apos;ve never really done this before..
        /// </summary>
        internal static string GottenKilled {
            get {
                return ResourceManager.GetString("GottenKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see no {0} here..
        /// </summary>
        internal static string ISeeNo {
            get {
                return ResourceManager.GetString("ISeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is now pitch dark.  If you proceed, you will likely fall into a pit..
        /// </summary>
        internal static string ItsPitchDark {
            get {
                return ResourceManager.GetString("ItsPitchDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a lamp shining nearby..
        /// </summary>
        internal static string LampShining {
            get {
                return ResourceManager.GetString("LampShining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a maze of twisty passages, all alike..
        /// </summary>
        internal static string Maze {
            get {
                return ResourceManager.GetString("Maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suddenly, a mummy creeps up behind you!! &quot;I&apos;m the keeper of the tomb&quot;, he wails, &quot;I take these treasures and put them in the chest deep in the maze!&quot; He grabs your treasure and vanishes into the gloom..
        /// </summary>
        internal static string MummyStealsTreasures {
            get {
                return ResourceManager.GetString("MummyStealsTreasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I no longer seem to remember how it was you got here..
        /// </summary>
        internal static string NoLongerRememberHowYouGotHere {
            get {
                return ResourceManager.GetString("NoLongerRememberHowYouGotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not carrying anything..
        /// </summary>
        internal static string NotCarryingAnything {
            get {
                return ResourceManager.GetString("NotCarryingAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing here to climb. Use up or out to leave the pit..
        /// </summary>
        internal static string NothingToClimb {
            get {
                return ResourceManager.GetString("NothingToClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve over-watered the plant! It&apos;s shrivelling up!.
        /// </summary>
        internal static string OverwateredPlant {
            get {
                return ResourceManager.GetString("OverwateredPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a twelve foot bean stalk stretching up out of the pit, bellowing &quot;Water... Water...&quot;.
        /// </summary>
        internal static string PlantBellowing {
            get {
                return ResourceManager.GetString("PlantBellowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant grows explosively, almost filling the bottom of the pit..
        /// </summary>
        internal static string PlantGrows {
            get {
                return ResourceManager.GetString("PlantGrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a tiny plant in the pit, murmuring &quot;Water, Water, ...&quot;.
        /// </summary>
        internal static string PlantMurmuring {
            get {
                return ResourceManager.GetString("PlantMurmuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant spurts into furious growth for a few seconds..
        /// </summary>
        internal static string PlantSpurts {
            get {
                return ResourceManager.GetString("PlantSpurts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are standing before the entrance of a pyramid. Around you is a desert..
        /// </summary>
        internal static string Room1 {
            get {
                return ResourceManager.GetString("Room1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in an awkward sloping east/west corridor..
        /// </summary>
        internal static string Room10 {
            get {
                return ResourceManager.GetString("Room10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a splendid chamber thirty feet high. The walls are frozen rivers of orange stone. An awkward corridor and a good passage exit from the east and west sides of the chamber..
        /// </summary>
        internal static string Room11 {
            get {
                return ResourceManager.GetString("Room11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At your feet is a small pit breathing traces of white mist. An east passage ends here except for a small crack leading on. Rough stone steps lead down the pit..
        /// </summary>
        internal static string Room12 {
            get {
                return ResourceManager.GetString("Room12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at one end of a vast hall stretching forward out of sight to the west. There are openings to either side. Nearby, a wide stone staircase leads downward. The hall is very musty and a cold wind blows up the staircase. There is a passage at the top of a dome behind you. Rought stone steps lead up the dome..
        /// </summary>
        internal static string Room13 {
            get {
                return ResourceManager.GetString("Room13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a low room with a hieroglyph on the wall. It translates &quot;You won&apos;t get it up the steps&quot;..
        /// </summary>
        internal static string Room14 {
            get {
                return ResourceManager.GetString("Room14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the east bank of a bottomless pit stretching across the hall. The mist is quite thick here, and the pit is too wide to jump..
        /// </summary>
        internal static string Room15 {
            get {
                return ResourceManager.GetString("Room15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the pharaoh&apos;s chamber, with passages off in all directions..
        /// </summary>
        internal static string Room16 {
            get {
                return ResourceManager.GetString("Room16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the south side chamber..
        /// </summary>
        internal static string Room17 {
            get {
                return ResourceManager.GetString("Room17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the west side of the bottomless pit in the hall of gods..
        /// </summary>
        internal static string Room18 {
            get {
                return ResourceManager.GetString("Room18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of the hall of gods. A low wide pass continues west and another goes north. To the south is a little passage six feet off the floor..
        /// </summary>
        internal static string Room19 {
            get {
                return ResourceManager.GetString("Room19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the entrance to the pyramid. A hole in the floor leads to a passage beneath the surface..
        /// </summary>
        internal static string Room2 {
            get {
                return ResourceManager.GetString("Room2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at east end of a very long hall apparently without side chambers. To the east a low wide crawl slants up. To the north a round two foot hole slants down..
        /// </summary>
        internal static string Room20 {
            get {
                return ResourceManager.GetString("Room20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of a very long featureless hall. The hall joins up with a narrow north/south passage..
        /// </summary>
        internal static string Room21 {
            get {
                return ResourceManager.GetString("Room21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at a crossover of a high N/S passage and a low E/W one..
        /// </summary>
        internal static string Room22 {
            get {
                return ResourceManager.GetString("Room22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the west throne chamber. A passage continues west and up from here..
        /// </summary>
        internal static string Room24 {
            get {
                return ResourceManager.GetString("Room24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a low N/S passage at a hole in the floor. The hole goes down to an E/W passage..
        /// </summary>
        internal static string Room25 {
            get {
                return ResourceManager.GetString("Room25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a large room, with a passage to the south, and a wall of broken rock to the east. There is a panel on the north wall..
        /// </summary>
        internal static string Room26 {
            get {
                return ResourceManager.GetString("Room26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Anubis..
        /// </summary>
        internal static string Room27 {
            get {
                return ResourceManager.GetString("Room27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the brink of a large pit. You could climb down, but you would not be able to climb back up. The maze continues on this level..
        /// </summary>
        internal static string Room52 {
            get {
                return ResourceManager.GetString("Room52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a dirty broken passage. To the east is a crawl. To the west is a large passage. Above you is a hole to another passage..
        /// </summary>
        internal static string Room54 {
            get {
                return ResourceManager.GetString("Room54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the brink of a small clean climbable pit. A crawl leads west..
        /// </summary>
        internal static string Room55 {
            get {
                return ResourceManager.GetString("Room55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the bottom of a small pit with a little stream, which enters and exits through tiny slits..
        /// </summary>
        internal static string Room56 {
            get {
                return ResourceManager.GetString("Room56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the room of Bes, whose picture is on the wall. There is a big hole in the floor. There is a passage leading east..
        /// </summary>
        internal static string Room57 {
            get {
                return ResourceManager.GetString("Room57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at a complex junction. A low hands and knees passage from the north joins a higher crawl from the east to make a walking passage going west. There is also a large room above. The air is damp here..
        /// </summary>
        internal static string Room58 {
            get {
                return ResourceManager.GetString("Room58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the underworld anteroom of Seker. Passages go east, west, and up. Human bones are strewn about on the floor. Hieroglyphics on the wall roughly translate to &quot;Those who proceed east may never return.&quot;..
        /// </summary>
        internal static string Room59 {
            get {
                return ResourceManager.GetString("Room59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the land of dead. Passages lead off in &gt;all&lt; directions..
        /// </summary>
        internal static string Room60 {
            get {
                return ResourceManager.GetString("Room60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in a large room with ancient drawings on all walls. The pictures depict Atum, a pharaoh wearing the double crown. A shallow passage proceeds downward, and a somewhat steeper one leads up. A low hands and knees passage enters from the south..
        /// </summary>
        internal static string Room61 {
            get {
                return ResourceManager.GetString("Room61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a chamber whose wall contains a picture of a man wearing the lunar disk on his head. He is the god Khons, the moon god..
        /// </summary>
        internal static string Room62 {
            get {
                return ResourceManager.GetString("Room62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a long sloping corridor with ragged walls..
        /// </summary>
        internal static string Room63 {
            get {
                return ResourceManager.GetString("Room63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a cul-de-sac about eight feet across..
        /// </summary>
        internal static string Room64 {
            get {
                return ResourceManager.GetString("Room64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Horus, a long east/west passage with holes everywhere. To explore at random, select north, south, up, or down..
        /// </summary>
        internal static string Room65 {
            get {
                return ResourceManager.GetString("Room65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a large low circular chamber whose floor is an immense slab fallen from the ceiling. East and west there once were large passages, but they are now filled with sand. Low small passages go north and south..
        /// </summary>
        internal static string Room66 {
            get {
                return ResourceManager.GetString("Room66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Nekhebet, a woman with the head of a vulture, wearing the crown of Egypt. A passage exits to the south..
        /// </summary>
        internal static string Room68 {
            get {
                return ResourceManager.GetString("Room68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a small chamber beneath a hole from the surface. A low crawl leads inward to the west. Hieroglyphics on the wall translate, &quot;Curse all who enter this sacred crypt.&quot;.
        ///
        ///.
        /// </summary>
        internal static string Room7 {
            get {
                return ResourceManager.GetString("Room7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passage here is blocked by a fallen block..
        /// </summary>
        internal static string Room70 {
            get {
                return ResourceManager.GetString("Room70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Osiris. The ceiling is too high up for your lamp to show it. Passages lead east, north, and south..
        /// </summary>
        internal static string Room71 {
            get {
                return ResourceManager.GetString("Room71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the priest&apos;s bedroom. The walls are covered with curtains, the floor with a thick pile carpet. Moss covers the ceiling..
        /// </summary>
        internal static string Room72 {
            get {
                return ResourceManager.GetString("Room72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the chamber of the high priest. Ancient drawings cover the walls. An extremely tight tunnel leads west. It looks like a tight squeeze. Another passage leads SE..
        /// </summary>
        internal static string Room73 {
            get {
                return ResourceManager.GetString("Room73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the high priest&apos;s treasure room lit by an eerie green light. A narrow tunnel exits to the east..
        /// </summary>
        internal static string Room76 {
            get {
                return ResourceManager.GetString("Room76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a long, narrow corridor stretching out of sight to the west. At the eastern end is a hole through which you can see a profusion of leaves..
        /// </summary>
        internal static string Room77 {
            get {
                return ResourceManager.GetString("Room77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the east end of the twopit room. The floor here is littered with thin rock slabs, which make it easy to descend the pits. There is a path here bypassing the pits to connect passages east and west. There are holes all over, but the only big one is on the wall directly over the west pit where you can&apos;t get to it..
        /// </summary>
        internal static string Room78 {
            get {
                return ResourceManager.GetString("Room78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the eastern pit in the twopit room..
        /// </summary>
        internal static string Room79 {
            get {
                return ResourceManager.GetString("Room79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are crawling over pebbles in a low passage. There is a dim light at the east end of the passage..
        /// </summary>
        internal static string Room8 {
            get {
                return ResourceManager.GetString("Room8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of the twopit room. There is a large hole in the wall above the pit at this end of the room..
        /// </summary>
        internal static string Room80 {
            get {
                return ResourceManager.GetString("Room80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the west pit in the twopit room. There is a large hole in the wall about twenty five feet above you..
        /// </summary>
        internal static string Room81 {
            get {
                return ResourceManager.GetString("Room81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a room filled with broken shards of ancient egyptian crafts. An awkward corridor leads upward and west..
        /// </summary>
        internal static string Room9 {
            get {
                return ResourceManager.GetString("Room9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t fit this big sarcophagus through that little passage!.
        /// </summary>
        internal static string SarcophagusDoesntFit {
            get {
                return ResourceManager.GetString("SarcophagusDoesntFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t get by the serpent..
        /// </summary>
        internal static string SerpentBlocks {
            get {
                return ResourceManager.GetString("SerpentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a shiny brass lamp nearby..
        /// </summary>
        internal static string ShinyBrassLamp {
            get {
                return ResourceManager.GetString("ShinyBrassLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue box.
        /// </summary>
        internal static string StatueBox {
            get {
                return ResourceManager.GetString("StatueBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to try to reincarnate you?.
        /// </summary>
        internal static string TryToReincarnate {
            get {
                return ResourceManager.GetString("TryToReincarnate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a massive vending machine here. The instructions on it read- &quot;Drop coins here to receive fresh batteries&quot;..
        /// </summary>
        internal static string VendingMachine {
            get {
                return ResourceManager.GetString("VendingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} What?.
        /// </summary>
        internal static string VerbWhat {
            get {
                return ResourceManager.GetString("VerbWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        internal static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want me to do with the {0} ?.
        /// </summary>
        internal static string WhatDoYouWantToDoWith {
            get {
                return ResourceManager.GetString("WhatDoYouWantToDoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have scored {0: 0000;-0000} out of 0220, using {1:0000} turns..
        /// </summary>
        internal static string YouHaveScored {
            get {
                return ResourceManager.GetString("YouHaveScored", resourceCulture);
            }
        }
    }
}
