//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyramid2000.Engine {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pyramid2000.Engine.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already carrying it..
        /// </summary>
        internal static string AlreadyCarryingIt {
            get {
                return ResourceManager.GetString("AlreadyCarryingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t carrying it..
        /// </summary>
        internal static string ArentCarryingIt {
            get {
                return ResourceManager.GetString("ArentCarryingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacking the serpent both doesn&apos;t work and is very dangerous..
        /// </summary>
        internal static string AttackingSerpentFails {
            get {
                return ResourceManager.GetString("AttackingSerpentFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A huge green fierce serpent bars the way!.
        /// </summary>
        internal static string BarredBySerpent {
            get {
                return ResourceManager.GetString("BarredBySerpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batteries.
        /// </summary>
        internal static string Batteries {
            get {
                return ResourceManager.GetString("Batteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are fresh batteries here..
        /// </summary>
        internal static string BatteriesFreshLongDesc {
            get {
                return ResourceManager.GetString("BatteriesFreshLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some worn-out batteries have been discarded nearby..
        /// </summary>
        internal static string BatteriesWornLongDesc {
            get {
                return ResourceManager.GetString("BatteriesWornLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is beyond your power to do that..
        /// </summary>
        internal static string BeyondYourPower {
            get {
                return ResourceManager.GetString("BeyondYourPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bird statue comes to life and attacks the serpent and in an astounding flurry, drives the serpent away. The bird turns back into a statue..
        /// </summary>
        internal static string BirdAlive {
            get {
                return ResourceManager.GetString("BirdAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird statue in box.
        /// </summary>
        internal static string BirdBoxed {
            get {
                return ResourceManager.GetString("BirdBoxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a bird statue in the box..
        /// </summary>
        internal static string BirdBoxedLongDesc {
            get {
                return ResourceManager.GetString("BirdBoxedLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not hungry. Besides, you have no bird seed..
        /// </summary>
        internal static string BirdNotHungry {
            get {
                return ResourceManager.GetString("BirdNotHungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bird statue is now dead. Its body disappears..
        /// </summary>
        internal static string BirdStatueDead {
            get {
                return ResourceManager.GetString("BirdStatueDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small bottle.
        /// </summary>
        internal static string Bottle {
            get {
                return ResourceManager.GetString("Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bottle is already full..
        /// </summary>
        internal static string BottleAlreadyFull {
            get {
                return ResourceManager.GetString("BottleAlreadyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a bottle here..
        /// </summary>
        internal static string BottleLongDesc {
            get {
                return ResourceManager.GetString("BottleLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass Lantern.
        /// </summary>
        internal static string BrassLantern {
            get {
                return ResourceManager.GetString("BrassLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stone bridge now spans the bottomless pit..
        /// </summary>
        internal static string BridgeAppears {
            get {
                return ResourceManager.GetString("BridgeAppears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone bridge has retracted!.
        /// </summary>
        internal static string BridgeRetracted {
            get {
                return ResourceManager.GetString("BridgeRetracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the pit with a broken neck..
        /// </summary>
        internal static string BrokenNeck {
            get {
                return ResourceManager.GetString("BrokenNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t be serious!.
        /// </summary>
        internal static string CantBeSerious {
            get {
                return ResourceManager.GetString("CantBeSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t carry anything more. You&apos;ll have to drop something first..
        /// </summary>
        internal static string CantCarryAnymore {
            get {
                return ResourceManager.GetString("CantCarryAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can lift the statue, but you cannot carry it..
        /// </summary>
        internal static string CantCarryStatue {
            get {
                return ResourceManager.GetString("CantCarryStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no way across the bottomless pit..
        /// </summary>
        internal static string CantCrossPit {
            get {
                return ResourceManager.GetString("CantCrossPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t fill that..
        /// </summary>
        internal static string CantFillThat {
            get {
                return ResourceManager.GetString("CantFillThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t fit through the two-inch slit!.
        /// </summary>
        internal static string CantFitThroughTwoInchSlit {
            get {
                return ResourceManager.GetString("CantFitThroughTwoInchSlit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t pour that..
        /// </summary>
        internal static string CantPourThat {
            get {
                return ResourceManager.GetString("CantPourThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure chest.
        /// </summary>
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pharaoh&apos;s treasure chest is here!.
        /// </summary>
        internal static string ChestLongDesc {
            get {
                return ResourceManager.GetString("ChestLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve climbed up the plant and out of the pit..
        /// </summary>
        internal static string ClimbedPlant {
            get {
                return ResourceManager.GetString("ClimbedPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clamber up the plant and scurry through the hole at the top..
        /// </summary>
        internal static string ClimbPlant {
            get {
                return ResourceManager.GetString("ClimbPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare coins.
        /// </summary>
        internal static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are many coins here!.
        /// </summary>
        internal static string CoinsLongDesc {
            get {
                return ResourceManager.GetString("CoinsLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crack is far too small for you to follow..
        /// </summary>
        internal static string CrackTooSmall {
            get {
                return ResourceManager.GetString("CrackTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled around in some little holes and found your way blocked by a fallen slab. You are now back in the main passage..
        /// </summary>
        internal static string CrawledAround {
            get {
                return ResourceManager.GetString("CrawledAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled around in some little holes and wound up back in the main passage..
        /// </summary>
        internal static string CrawledAroundBackToMainPassage {
            get {
                return ResourceManager.GetString("CrawledAroundBackToMainPassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have crawled through a very low wide passage parallel to and north of the hall of gods..
        /// </summary>
        internal static string CrawlToPassage {
            get {
                return ResourceManager.GetString("CrawlToPassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I respectfully suggest you go across the bridge instead of jumping..
        /// </summary>
        internal static string CrossDontJump {
            get {
                return ResourceManager.GetString("CrossDontJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead end..
        /// </summary>
        internal static string DeadEnd {
            get {
                return ResourceManager.GetString("DeadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, it was delicious!.
        /// </summary>
        internal static string Delicious {
            get {
                return ResourceManager.GetString("Delicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the desert..
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several diamonds.
        /// </summary>
        internal static string Diamonds {
            get {
                return ResourceManager.GetString("Diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are diamonds here!.
        /// </summary>
        internal static string DiamondsLongDesc {
            get {
                return ResourceManager.GetString("DiamondsLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t make it..
        /// </summary>
        internal static string DidntMakeIt {
            get {
                return ResourceManager.GetString("DidntMakeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a small statue box discarded nearby..
        /// </summary>
        internal static string DiscardedStatueBox {
            get {
                return ResourceManager.GetString("DiscardedStatueBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dome is unclimbable..
        /// </summary>
        internal static string DomeUnclimbable {
            get {
                return ResourceManager.GetString("DomeUnclimbable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t be ridiculous!.
        /// </summary>
        internal static string DontBeRidiculous {
            get {
                return ResourceManager.GetString("DontBeRidiculous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how..
        /// </summary>
        internal static string DontKnowHow {
            get {
                return ResourceManager.GetString("DontKnowHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to apply that word here..
        /// </summary>
        internal static string DontKnowHowToApplyWord {
            get {
                return ResourceManager.GetString("DontKnowHowToApplyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know how to lock or unlock such a thing..
        /// </summary>
        internal static string DontKnowHowToLockUnlock {
            get {
                return ResourceManager.GetString("DontKnowHowToLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that word..
        /// </summary>
        internal static string DontKnowThatWord {
            get {
                return ResourceManager.GetString("DontKnowThatWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know what you mean..
        /// </summary>
        internal static string DontKnowWhatYouMean {
            get {
                return ResourceManager.GetString("DontKnowWhatYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t understand..
        /// </summary>
        internal static string DontUnderstand {
            get {
                return ResourceManager.GetString("DontUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have taken a drink from the stream. The water tastes strongly of minerals, but is not unpleasant. It is extremely cold..
        /// </summary>
        internal static string DrinkFromStream {
            get {
                return ResourceManager.GetString("DrinkFromStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something you&apos;re carrying won&apos;t fit through the tunnel with you. You&apos;d best take inventory and drop something..
        /// </summary>
        internal static string DropSomething {
            get {
                return ResourceManager.GetString("DropSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg-sized emerald.
        /// </summary>
        internal static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an emerald here the size of a plover&apos;s egg!.
        /// </summary>
        internal static string EmeraldLongDesc {
            get {
                return ResourceManager.GetString("EmeraldLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bottle is now empty..
        /// </summary>
        internal static string EmptyBottle {
            get {
                return ResourceManager.GetString("EmptyBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bottle is empty and the ground is wet..
        /// </summary>
        internal static string EmptyBottleWetGround {
            get {
                return ResourceManager.GetString("EmptyBottleWetGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sarcophagus creaks open, revealing nothing inside. It promptly snaps shut again..
        /// </summary>
        internal static string EmptySarcophagus {
            get {
                return ResourceManager.GetString("EmptySarcophagus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You fell into a pit and broke every bone in your body..
        /// </summary>
        internal static string FellIntoPit {
            get {
                return ResourceManager.GetString("FellIntoPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor is littered with worthless shards of pottery..
        /// </summary>
        internal static string FloorLitteredWithShards {
            get {
                return ResourceManager.GetString("FloorLitteredWithShards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasty food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is food here..
        /// </summary>
        internal static string FoodLongDesc {
            get {
                return ResourceManager.GetString("FoodLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are now some fresh batteries here..
        /// </summary>
        internal static string FreshBatteries {
            get {
                return ResourceManager.GetString("FreshBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a gigantic beam stalk stretching all the way up to the hole..
        /// </summary>
        internal static string GiganticBeanStalk {
            get {
                return ResourceManager.GetString("GiganticBeanStalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glistening pearl.
        /// </summary>
        internal static string GlisteningPearl {
            get {
                return ResourceManager.GetString("GlisteningPearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off to one side lies a glistening pearl!.
        /// </summary>
        internal static string GlisteningPearlLongDesc {
            get {
                return ResourceManager.GetString("GlisteningPearlLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large gold nugget.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a large sparkling nugget of gold here!.
        /// </summary>
        internal static string GoldLongDesc {
            get {
                return ResourceManager.GetString("GoldLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh dear, you seem to have gotten yourself killed.  I might be able to help you out, but I&apos;ve never really done this before..
        /// </summary>
        internal static string GottenKilled {
            get {
                return ResourceManager.GetString("GottenKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m as confused as you are!.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m game. Would you care to explain how?.
        /// </summary>
        internal static string ImGame {
            get {
                return ResourceManager.GetString("ImGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see no {0} here..
        /// </summary>
        internal static string ISeeNo {
            get {
                return ResourceManager.GetString("ISeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is now pitch dark. If you proceed, you will likely fall into a pit..
        /// </summary>
        internal static string ItsPitchDark {
            get {
                return ResourceManager.GetString("ItsPitchDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precious jewelry.
        /// </summary>
        internal static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is precious jewelry here!.
        /// </summary>
        internal static string JewelryLongDesc {
            get {
                return ResourceManager.GetString("JewelryLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweled key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a jewel-encrusted key here!.
        /// </summary>
        internal static string KeyLongDesc {
            get {
                return ResourceManager.GetString("KeyLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lamp is getting dim. You&apos;d best start wrapping this up, unless you can find some fresh batteries. I seem to recall there is a vending machine in the maze. Bring some coins with you..
        /// </summary>
        internal static string LampGettingDim {
            get {
                return ResourceManager.GetString("LampGettingDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lamp is getting dim. I&apos;m taking the liberty of replacing the batteries..
        /// </summary>
        internal static string LampGettingDimChangingBatteries {
            get {
                return ResourceManager.GetString("LampGettingDimChangingBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lamp is now off..
        /// </summary>
        internal static string LampIsNowOff {
            get {
                return ResourceManager.GetString("LampIsNowOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lamp is now on..
        /// </summary>
        internal static string LampIsNowOn {
            get {
                return ResourceManager.GetString("LampIsNowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lamp has run out of power..
        /// </summary>
        internal static string LampOutOfPower {
            get {
                return ResourceManager.GetString("LampOutOfPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a lamp shining nearby..
        /// </summary>
        internal static string LampShining {
            get {
                return ResourceManager.GetString("LampShining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I just lost my appetite..
        /// </summary>
        internal static string LostAppetite {
            get {
                return ResourceManager.GetString("LostAppetite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Egyptian weekly&quot;.
        /// </summary>
        internal static string Magazine {
            get {
                return ResourceManager.GetString("Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are a few recent issues of &quot;Egyptian weekly&quot; magazine here..
        /// </summary>
        internal static string MagazineLongDesc {
            get {
                return ResourceManager.GetString("MagazineLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a maze of twisty passages, all alike..
        /// </summary>
        internal static string Maze {
            get {
                return ResourceManager.GetString("Maze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suddenly, a mummy creeps up behind you!! &quot;I&apos;m the keeper of the tomb&quot;, he wails, &quot;I take these treasures and put them in the chest deep in the maze!&quot; He grabs your treasure and vanishes into the gloom..
        /// </summary>
        internal static string MummyStealsTreasures {
            get {
                return ResourceManager.GetString("MummyStealsTreasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden eggs.
        /// </summary>
        internal static string Nest {
            get {
                return ResourceManager.GetString("Nest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a large nest here, full of golden eggs!.
        /// </summary>
        internal static string NestLongDesc {
            get {
                return ResourceManager.GetString("NestLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I no longer seem to remember how it was you got here..
        /// </summary>
        internal static string NoLongerRememberHowYouGotHere {
            get {
                return ResourceManager.GetString("NoLongerRememberHowYouGotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no source of light..
        /// </summary>
        internal static string NoSourceOfLight {
            get {
                return ResourceManager.GetString("NoSourceOfLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not carrying anything..
        /// </summary>
        internal static string NotCarryingAnything {
            get {
                return ResourceManager.GetString("NotCarryingAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing happens..
        /// </summary>
        internal static string NothingHappens {
            get {
                return ResourceManager.GetString("NothingHappens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing here to climb. Use up or out to leave the pit..
        /// </summary>
        internal static string NothingToClimb {
            get {
                return ResourceManager.GetString("NothingToClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing here with which to fill the bottle..
        /// </summary>
        internal static string NothingToFillBottleWith {
            get {
                return ResourceManager.GetString("NothingToFillBottleWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have anything strong enough to open the sarcophagus..
        /// </summary>
        internal static string NotStrongEnoughToOpenSarcophagus {
            get {
                return ResourceManager.GetString("NotStrongEnoughToOpenSarcophagus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no way for you to go that direction..
        /// </summary>
        internal static string NoWayToGoThatDirection {
            get {
                return ResourceManager.GetString("NoWayToGoThatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve over-watered the plant! It&apos;s shrivelling up!.
        /// </summary>
        internal static string OverwateredPlant {
            get {
                return ResourceManager.GetString("OverwateredPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A glistening pearl falls out of the sarcophagus and rolls away. The sarcophagus snaps shut again..
        /// </summary>
        internal static string PearlFallsOut {
            get {
                return ResourceManager.GetString("PearlFallsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peculiar. Nothing unexpected happens..
        /// </summary>
        internal static string Peculiar {
            get {
                return ResourceManager.GetString("Peculiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velvet pillow.
        /// </summary>
        internal static string Pillow {
            get {
                return ResourceManager.GetString("Pillow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a twelve foot bean stalk stretching up out of the pit, bellowing &quot;Water... Water...&quot;.
        /// </summary>
        internal static string PlantBellowing {
            get {
                return ResourceManager.GetString("PlantBellowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant has exceptionally deep roots and cannot be pulled free..
        /// </summary>
        internal static string PlantCantBePulledFree {
            get {
                return ResourceManager.GetString("PlantCantBePulledFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant grows explosively, almost filling the bottom of the pit..
        /// </summary>
        internal static string PlantGrows {
            get {
                return ResourceManager.GetString("PlantGrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a tiny plant in the pit, murmuring &quot;Water, Water, ...&quot;.
        /// </summary>
        internal static string PlantMurmuring {
            get {
                return ResourceManager.GetString("PlantMurmuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant spurts into furious growth for a few seconds..
        /// </summary>
        internal static string PlantSpurts {
            get {
                return ResourceManager.GetString("PlantSpurts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d advise you to put down the sarcophagus before opening it!!.
        /// </summary>
        internal static string PutSarcophagusDown {
            get {
                return ResourceManager.GetString("PutSarcophagusDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are standing before the entrance of a pyramid. Around you is a desert..
        /// </summary>
        internal static string Room1 {
            get {
                return ResourceManager.GetString("Room1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in an awkward sloping east/west corridor..
        /// </summary>
        internal static string Room10 {
            get {
                return ResourceManager.GetString("Room10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a splendid chamber thirty feet high. The walls are frozen rivers of orange stone. An awkward corridor and a good passage exit from the east and west sides of the chamber..
        /// </summary>
        internal static string Room11 {
            get {
                return ResourceManager.GetString("Room11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At your feet is a small pit breathing traces of white mist. An east passage ends here except for a small crack leading on. Rough stone steps lead down the pit..
        /// </summary>
        internal static string Room12 {
            get {
                return ResourceManager.GetString("Room12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at one end of a vast hall stretching forward out of sight to the west. There are openings to either side. Nearby, a wide stone staircase leads downward. The hall is very musty and a cold wind blows up the staircase. There is a passage at the top of a dome behind you. Rought stone steps lead up the dome..
        /// </summary>
        internal static string Room13 {
            get {
                return ResourceManager.GetString("Room13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a low room with a hieroglyph on the wall. It translates &quot;You won&apos;t get it up the steps&quot;..
        /// </summary>
        internal static string Room14 {
            get {
                return ResourceManager.GetString("Room14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the east bank of a bottomless pit stretching across the hall. The mist is quite thick here, and the pit is too wide to jump..
        /// </summary>
        internal static string Room15 {
            get {
                return ResourceManager.GetString("Room15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the pharaoh&apos;s chamber, with passages off in all directions..
        /// </summary>
        internal static string Room16 {
            get {
                return ResourceManager.GetString("Room16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the south side chamber..
        /// </summary>
        internal static string Room17 {
            get {
                return ResourceManager.GetString("Room17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the west side of the bottomless pit in the hall of gods..
        /// </summary>
        internal static string Room18 {
            get {
                return ResourceManager.GetString("Room18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of the hall of gods. A low wide pass continues west and another goes north. To the south is a little passage six feet off the floor..
        /// </summary>
        internal static string Room19 {
            get {
                return ResourceManager.GetString("Room19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the entrance to the pyramid. A hole in the floor leads to a passage beneath the surface..
        /// </summary>
        internal static string Room2 {
            get {
                return ResourceManager.GetString("Room2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at east end of a very long hall apparently without side chambers. To the east a low wide crawl slants up. To the north a round two foot hole slants down..
        /// </summary>
        internal static string Room20 {
            get {
                return ResourceManager.GetString("Room20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of a very long featureless hall. The hall joins up with a narrow north/south passage..
        /// </summary>
        internal static string Room21 {
            get {
                return ResourceManager.GetString("Room21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at a crossover of a high N/S passage and a low E/W one..
        /// </summary>
        internal static string Room22 {
            get {
                return ResourceManager.GetString("Room22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the west throne chamber. A passage continues west and up from here..
        /// </summary>
        internal static string Room24 {
            get {
                return ResourceManager.GetString("Room24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a low N/S passage at a hole in the floor. The hole goes down to an E/W passage..
        /// </summary>
        internal static string Room25 {
            get {
                return ResourceManager.GetString("Room25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a large room, with a passage to the south, and a wall of broken rock to the east. There is a panel on the north wall..
        /// </summary>
        internal static string Room26 {
            get {
                return ResourceManager.GetString("Room26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Anubis..
        /// </summary>
        internal static string Room27 {
            get {
                return ResourceManager.GetString("Room27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the brink of a large pit. You could climb down, but you would not be able to climb back up. The maze continues on this level..
        /// </summary>
        internal static string Room52 {
            get {
                return ResourceManager.GetString("Room52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a dirty broken passage. To the east is a crawl. To the west is a large passage. Above you is a hole to another passage..
        /// </summary>
        internal static string Room54 {
            get {
                return ResourceManager.GetString("Room54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on the brink of a small clean climbable pit. A crawl leads west..
        /// </summary>
        internal static string Room55 {
            get {
                return ResourceManager.GetString("Room55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the bottom of a small pit with a little stream, which enters and exits through tiny slits..
        /// </summary>
        internal static string Room56 {
            get {
                return ResourceManager.GetString("Room56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the room of Bes, whose picture is on the wall. There is a big hole in the floor. There is a passage leading east..
        /// </summary>
        internal static string Room57 {
            get {
                return ResourceManager.GetString("Room57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at a complex junction. A low hands and knees passage from the north joins a higher crawl from the east to make a walking passage going west. There is also a large room above. The air is damp here..
        /// </summary>
        internal static string Room58 {
            get {
                return ResourceManager.GetString("Room58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the underworld anteroom of Seker. Passages go east, west, and up. Human bones are strewn about on the floor. Hieroglyphics on the wall roughly translate to &quot;Those who proceed east may never return.&quot;..
        /// </summary>
        internal static string Room59 {
            get {
                return ResourceManager.GetString("Room59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the land of dead. Passages lead off in &gt;all&lt; directions..
        /// </summary>
        internal static string Room60 {
            get {
                return ResourceManager.GetString("Room60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in a large room with ancient drawings on all walls. The pictures depict Atum, a pharaoh wearing the double crown. A shallow passage proceeds downward, and a somewhat steeper one leads up. A low hands and knees passage enters from the south..
        /// </summary>
        internal static string Room61 {
            get {
                return ResourceManager.GetString("Room61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a chamber whose wall contains a picture of a man wearing the lunar disk on his head. He is the god Khons, the moon god..
        /// </summary>
        internal static string Room62 {
            get {
                return ResourceManager.GetString("Room62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a long sloping corridor with ragged walls..
        /// </summary>
        internal static string Room63 {
            get {
                return ResourceManager.GetString("Room63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a cul-de-sac about eight feet across..
        /// </summary>
        internal static string Room64 {
            get {
                return ResourceManager.GetString("Room64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Horus, a long east/west passage with holes everywhere. To explore at random, select north, south, up, or down..
        /// </summary>
        internal static string Room65 {
            get {
                return ResourceManager.GetString("Room65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a large low circular chamber whose floor is an immense slab fallen from the ceiling. East and west there once were large passages, but they are now filled with sand. Low small passages go north and south..
        /// </summary>
        internal static string Room66 {
            get {
                return ResourceManager.GetString("Room66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Nekhebet, a woman with the head of a vulture, wearing the crown of Egypt. A passage exits to the south..
        /// </summary>
        internal static string Room68 {
            get {
                return ResourceManager.GetString("Room68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a small chamber beneath a hole from the surface. A low crawl leads inward to the west. Hieroglyphics on the wall translate, &quot;Curse all who enter this sacred crypt.&quot;.
        /// </summary>
        internal static string Room7 {
            get {
                return ResourceManager.GetString("Room7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passage here is blocked by a fallen block..
        /// </summary>
        internal static string Room70 {
            get {
                return ResourceManager.GetString("Room70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the chamber of Osiris. The ceiling is too high up for your lamp to show it. Passages lead east, north, and south..
        /// </summary>
        internal static string Room71 {
            get {
                return ResourceManager.GetString("Room71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the priest&apos;s bedroom. The walls are covered with curtains, the floor with a thick pile carpet. Moss covers the ceiling..
        /// </summary>
        internal static string Room72 {
            get {
                return ResourceManager.GetString("Room72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the chamber of the high priest. Ancient drawings cover the walls. An extremely tight tunnel leads west. It looks like a tight squeeze. Another passage leads SE..
        /// </summary>
        internal static string Room73 {
            get {
                return ResourceManager.GetString("Room73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the high priest&apos;s treasure room lit by an eerie green light. A narrow tunnel exits to the east..
        /// </summary>
        internal static string Room76 {
            get {
                return ResourceManager.GetString("Room76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a long, narrow corridor stretching out of sight to the west. At the eastern end is a hole through which you can see a profusion of leaves..
        /// </summary>
        internal static string Room77 {
            get {
                return ResourceManager.GetString("Room77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the east end of the twopit room. The floor here is littered with thin rock slabs, which make it easy to descend the pits. There is a path here bypassing the pits to connect passages east and west. There are holes all over, but the only big one is on the wall directly over the west pit where you can&apos;t get to it..
        /// </summary>
        internal static string Room78 {
            get {
                return ResourceManager.GetString("Room78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the eastern pit in the twopit room..
        /// </summary>
        internal static string Room79 {
            get {
                return ResourceManager.GetString("Room79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are crawling over pebbles in a low passage. There is a dim light at the east end of the passage..
        /// </summary>
        internal static string Room8 {
            get {
                return ResourceManager.GetString("Room8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the west end of the twopit room. There is a large hole in the wall above the pit at this end of the room..
        /// </summary>
        internal static string Room80 {
            get {
                return ResourceManager.GetString("Room80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the bottom of the west pit in the twopit room. There is a large hole in the wall about twenty five feet above you..
        /// </summary>
        internal static string Room81 {
            get {
                return ResourceManager.GetString("Room81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a room filled with broken shards of ancient egyptian crafts. An awkward corridor leads upward and west..
        /// </summary>
        internal static string Room9 {
            get {
                return ResourceManager.GetString("Room9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubbing the electric lamp is not particularly rewarding. Anyway, nothing exciting happens..
        /// </summary>
        internal static string RubbingNothingHappens {
            get {
                return ResourceManager.GetString("RubbingNothingHappens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarcophagus &gt;groan&lt;.
        /// </summary>
        internal static string Sarcophagus {
            get {
                return ResourceManager.GetString("Sarcophagus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t fit this big sarcophagus through that little passage!.
        /// </summary>
        internal static string SarcophagusDoesntFit {
            get {
                return ResourceManager.GetString("SarcophagusDoesntFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a sarcophagus here with it&apos;s cover tightly closed..
        /// </summary>
        internal static string SarcophagusLongDesc {
            get {
                return ResourceManager.GetString("SarcophagusLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scepter.
        /// </summary>
        internal static string Scepter {
            get {
                return ResourceManager.GetString("Scepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t get by the serpent..
        /// </summary>
        internal static string SerpentBlocks {
            get {
                return ResourceManager.GetString("SerpentBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serpent has now devoured your bird statue..
        /// </summary>
        internal static string SerpentEatenBird {
            get {
                return ResourceManager.GetString("SerpentEatenBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing here it wants to eat - except perhaps you..
        /// </summary>
        internal static string SerpentHasNothingToEat {
            get {
                return ResourceManager.GetString("SerpentHasNothingToEat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a shiny brass lamp nearby..
        /// </summary>
        internal static string ShinyBrassLamp {
            get {
                return ResourceManager.GetString("ShinyBrassLamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver bars.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are bars of silver here!.
        /// </summary>
        internal static string SilverLongDesc {
            get {
                return ResourceManager.GetString("SilverLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small velvet pillow lies on the floor..
        /// </summary>
        internal static string SmallVelvetPillow {
            get {
                return ResourceManager.GetString("SmallVelvetPillow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue box.
        /// </summary>
        internal static string StatueBox {
            get {
                return ResourceManager.GetString("StatueBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you approach the statue, it comes to life and flies across the chamber where it lands and returns to stone..
        /// </summary>
        internal static string StatueComesToLife {
            get {
                return ResourceManager.GetString("StatueComesToLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird statue in box..
        /// </summary>
        internal static string StatueInBox {
            get {
                return ResourceManager.GetString("StatueInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A statue of the bird god is sitting here..
        /// </summary>
        internal static string StatueOfBirdGod {
            get {
                return ResourceManager.GetString("StatueOfBirdGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone is very strong and is impervious to attack..
        /// </summary>
        internal static string StoneVeryStrong {
            get {
                return ResourceManager.GetString("StoneVeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A three foot scepter with an ankh on an end lies nearby..
        /// </summary>
        internal static string ThreeFootScepter {
            get {
                return ResourceManager.GetString("ThreeFootScepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to try to reincarnate you?.
        /// </summary>
        internal static string TryToReincarnate {
            get {
                return ResourceManager.GetString("TryToReincarnate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am unsure how you are facing. Use compass points..
        /// </summary>
        internal static string UnsureHowYouAreFacing {
            get {
                return ResourceManager.GetString("UnsureHowYouAreFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know in from out here. Use compass points..
        /// </summary>
        internal static string UseCompassPoints {
            get {
                return ResourceManager.GetString("UseCompassPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vase.
        /// </summary>
        internal static string Vase {
            get {
                return ResourceManager.GetString("Vase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vase drops with a delicate crash..
        /// </summary>
        internal static string VaseDropsWithCrash {
            get {
                return ResourceManager.GetString("VaseDropsWithCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have taken the vase and hurled it delicately to the ground..
        /// </summary>
        internal static string VaseHurledToGround {
            get {
                return ResourceManager.GetString("VaseHurledToGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vase is now resting, delicately, on a velvet pillow..
        /// </summary>
        internal static string VasePillowLongDesc {
            get {
                return ResourceManager.GetString("VasePillowLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vase is now resting, delicately, on a velvet pillow..
        /// </summary>
        internal static string VaseRestingOnPillow {
            get {
                return ResourceManager.GetString("VaseRestingOnPillow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a delicate, precious, vase here!.
        /// </summary>
        internal static string VaseSoloLongDesc {
            get {
                return ResourceManager.GetString("VaseSoloLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a massive vending machine here. The instructions on it read- &quot;Drop coins here to receive fresh batteries&quot;..
        /// </summary>
        internal static string VendingMachine {
            get {
                return ResourceManager.GetString("VendingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} what?.
        /// </summary>
        internal static string VerbWhat {
            get {
                return ResourceManager.GetString("VerbWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water in the bottle.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is water in the bottle..
        /// </summary>
        internal static string WaterLongDesc {
            get {
                return ResourceManager.GetString("WaterLongDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to pyramid!!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What?.
        /// </summary>
        internal static string What {
            get {
                return ResourceManager.GetString("What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want me to do with the {0} ?.
        /// </summary>
        internal static string WhatDoYouWantToDoWith {
            get {
                return ResourceManager.GetString("WhatDoYouWantToDoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently holding the following:.
        /// </summary>
        internal static string YouAreHolding {
            get {
                return ResourceManager.GetString("YouAreHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have scored {0: 0000;-0000} out of a possible 0220, using {1:0000} turns..
        /// </summary>
        internal static string YouHaveScored {
            get {
                return ResourceManager.GetString("YouHaveScored", resourceCulture);
            }
        }
    }
}
